### ISSUE TITLE
Allow spaces in CIID

### ISSUE THREAD

**Issue by ZacWarham** [PrairieLearn/PrairieLearn#13174]
### Details

This was raised a few months ago in Slack, Spaces are allowed in CIID but blocked in the UI

<img width="581" height="242" alt="Image" src="https://github.com/user-attachments/assets/1bd4af70-f9ea-472c-8a4e-8c153544e4d5" />

I haven't gotten around to submitting a PR yet so thought I would open as an issue for discussion

**Comment by ZacWarham** [comment]
Simple fix from what I see would be to add spaces to the regex but wondering if it is worth complicating the pattern match to stop spaces at the start and end of the CIID

**Comment by nwalters512** [comment]
> Simple fix from what I see would be to add spaces to the regex but wondering if it is worth complicating the pattern match to stop spaces at the start and end of the CIID

We should be using `.trim()` on the backend before persisting. If we aren't already, we should do that.

Note that assessments and questions probably need the same treatment, both for editing existing ones but also creating new ones.

**Comment by jonatanschroeder** [comment]
Related: #9908.

**Comment by reteps** [comment]
Related: #13439

**Comment by reteps** [comment]
This is now solved by #13533, which allows you to do spaces/etc. if you modify on disk. As long as you don't change the CIID in the UI, then you can still edit the question. This is mainly to support spaces in CIID from existing questions being edited in the UI, as in the UI we are moving away from allowing spaces in this field.

**Comment by nwalters512** [comment]
Marking as not planned, as we still do not allow spaces when editing in the UI. This is not set in stone; we can revisit this if folks have a compelling reason to allow this.
