### ISSUE TITLE
Issue link missing variant_id

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1980]
https://prairielearn.engr.illinois.edu/pl/course_instance/31429/instructor/issues?q=qid%3Amc-dll-delete-fa17-01c

One of the two issues at the page above has an invalid URL because it ends with `variant_id=` without the actual `variant_id` value.

Reported by @echuber2

**Comment by jonatanschroeder** [comment]
I believe this was fixed in #3568, but I can't test your case.

**Comment by mwest1066** [comment]
I'm afraid this didn't fix the issue above. For future reference, the page with the error is now:

https://www.prairielearn.org/pl/course_instance/31429/instructor/course_admin/issues?q=qid%3Amc-dll-delete-fa17-01c

It's the second-to-last issue on that page.

**Comment by mwest1066** [comment]
The "instructor view" link on the issues page above links to `https://www.prairielearn.org/pl/course_instance/31429/instructor/question/675842/preview?variant_id=` (with no `variant_id` specified on the end).

**Comment by jonatanschroeder** [comment]
I'm not an instructor there, so I can't check your case (no instructor permission), but the issues in my own courses all have the variant_id. Is there anything particularly unique about that issue? Is it manually or automatically reported? By a student or an instructor? Does it have an instance question ID (i.e., was it created in student mode)?

**Comment by jonatanschroeder** [comment]
Nevermind, found a case in my course that has this problem. I'll investigate and figure it out.

**Comment by jonatanschroeder** [comment]
It seems the case in my course was an assessment instance that was deleted. Could this be the case there? The foreign key on `issues.variant_id` has `ON DELETE SET NULL`. If that is the case, one possible fix would be to change the foreign key in `variants.instance_question_id` to `ON DELETE SET NULL` as well, so the variant is not deleted when the assessment instance is deleted, but that could lead to dangling variants...

**Comment by jonatanschroeder** [comment]
Or by implementing soft-delete in assessment instances 😄

**Comment by mwest1066** [comment]
> It seems the case in my course was an assessment instance that was deleted. Could this be the case there? The foreign key on `issues.variant_id` has `ON DELETE SET NULL`. If that is the case, one possible fix would be to change the foreign key in `variants.instance_question_id` to `ON DELETE SET NULL` as well, so the variant is not deleted when the assessment instance is deleted, but that could lead to dangling variants...

Good find! That does look like what's happened here. Both `issues.variant_id` and `issues.instance_question_id` are NULL on the bad issue.

> Or by implementing soft-delete in assessment instances 😄

I'm not in love with the idea of dangling variants, I have to say 😄

Some possibilities are:
1. Soft-delete assessment instances, as you suggest. I like this, but I'm worried that it's a lot of work. But maybe not? It depends on how many places we'd need to add `WHERE deleted_at IS NULL`.
2. Change the `issues.variant_id` to have `ON DELETE CASCADE`, so that we also delete the issue when deleting the assessment instance.
3. On the issues page, check whether `variant_id` is NULL when creating the link and say something like "variant has been deleted" rather than showing the link.

Thoughts?

**Comment by jonatanschroeder** [comment]
Is this a duplicate of (or superceded by) #13608?
