### ISSUE TITLE
pl-multiple-choice KeyError: 'feedback' 

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#4823]
Receiving a flood of system-generated errors on `pl-multiple-choice` questions.

https://www.prairielearn.org/pl/course_instance/128821/instructor/question/5747329/preview?variant_id=40313018 

```python
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 182, in <module>
    worker_loop()
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 128, in worker_loop
    val = method(*args)
  File "/PrairieLearn/elements/pl-multiple-choice/pl-multiple-choice.py", line 350, in grade
    feedback = option['feedback']
KeyError: 'feedback'
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 194, in <module>
    raise Exception('worker process exited unexpectedly with status %d' % status)
Exception: worker process exited unexpectedly with status 256
```

**Comment by mwest1066** [comment]
Yes, many apologies, it was caused by a bug in a new option for the `pl-multiple-choice` element. A fix has already been merged in #4821 but we are holding off on deploying the fix until the current batch of CBTF exams finishes at 10pm CT tonight.

**Comment by wangvsa** [comment]
Is it fixed now?

**Comment by pthangeda** [comment]
@mwest1066 could you confirm if the fix in #4821 has been deployed? I am still receiving the same errors (the latest being a couple of minutes ago).

**Comment by mwest1066** [comment]
We are still seeing high load on the Illinois server (turns out an ECE 110 HW is due at midnight). At this point I'm intending to deploy the fix at 6am CT tomorrow when there will be little student activity. Sorry for the delay!

**Comment by mwest1066** [comment]
The fix in #4821 has now been deployed.

With this new fix, students will still see the red error box on their existing questions, but the question can in fact be answered. Students should ignore the red error box and answer the question anyway. The question will work correctly, and after they have answered it once they can click "New variant" to get a new error-free version of the question (on Homeworks).

Many apologies to everyone who was impacted by this bug!
